### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by ReekyMarko** [kori/libra#4]
On my computer at least, libra seems to have a really high usage of CPU. More than firefox during the time of writing this issue.

![image](https://user-images.githubusercontent.com/16839187/62411028-8711c780-b5dd-11e9-9771-a81efe5e50dc.png)

**Comment by kori** [comment]
This occurs when mpd is paused, it's related to issue #2. I haven't sat down to fix it, though.

**Comment by ReekyMarko** [comment]
Okay, sorry for spamming

**Comment by kori** [comment]
It's no problem. It's not obvious at first glance.
